baseurl: "http://wobbly.earth"
languageCode: "en-us"
title: "Wobbly Earth"
description: "Academic homepage of Roelof Rietbroek"
theme: "HugoMDL"
MetaDataFormat: "yaml"
ignoreFiles: "\\.swp$"
pygmentsstyle: "friendly"
googleAnalytics: "UA-84784436-1"
sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"
taxonomies:
    tag: "tags"
    category: "categories"
permalinks:
    page: "/:title/"
    about: "/:filename/"
params:
    author: "Roelof Rietbroek"
    avatar: "/images/avatar.jpg"
    postimage: "/images/planken.jpg"
    background: "/images/background.jpg"
    description: "Academic homepage of Roelof Rietbroek"
    image: "/images/avatar.jpg" #for frontpage profile card
    logo: "/static/images/WBlogo_64x64.png"
    website: "http://www.igg.uni-bonn.de/apmg/index.php?id=rietbroek"
    email: "roelof@wobbly.earth"
    twitter: "https://twitter.com/r_rietje"
    github: "https://github.com/strawpants/"
    gscholar: "https://scholar.google.com/citations?user=PojYuOAAAAAJ&hl=en"
#    linkedin: "https://linkedin.com/in/firstname_lastname/"
    facebook: "https://facebook.com/rrietbroek/"
    copyrightyear: "2016"
    frontpageposts: 3 #number of post cards to display on frontpage
    
