baseurl = "http://strawpants.github.io/public/"
languageCode = "en-us"
title = "Academic Homepage of Roelof Rietbroek"
theme = "HugoMDL"
MetaDataFormat = "yaml"
[permalinks]
	page = "/:title/"
	about = "/:filename/"
[params]
    author = "Roelof Rietbroek"
    avatar = "/images/avatar.png"
    background = "/images/background.jpg"
    description = "A place to publish my incomprehensible ramblings" #meta description
    image = "/images/avatar-192x210.png" #for frontpage profile card
    website = "example.com"
    email = "roelof@geod.uni-bonn.de"
    twitter = "https://twitter.com/r_rietje"
    github = "https://github.com/strawpants/"
#    linkedin = "https://linkedin.com/in/firstname_lastname/"
#    facebook = "https://facebook.com/firstname_lastname/"
    copyrightyear = "2016"
    frontpageposts = 6 #number of post cards to display on frontpage
    