baseurl: "http://wobbly.earth"
languageCode: "en-us"
title: "Wobbly Earth"
description: "Academic homepage of Roelof Rietbroek"
theme: "HugoMDL"
MetaDataFormat: "yaml"
ignoreFiles:
    - "\\.swp$"
pygmentsstyle: "friendly"
googleAnalytics: "UA-84784436-1"
sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"
taxonomies:
    tag: "tags"
    category: "categories"
    level: "levels"
permalinks:
    page: "/:title/"
    about: "/:filename/"
params:
    title: "Wobbly Earth"
    author: "Roelof  Rietbroek"
    avatar: "/images/avatar.jpg"
    postimage: "/images/schuifmaat.jpg"
    ogimage: "/images/Screenshot_home_og.png"
    background: "/images/background.jpg"
    description: "Academic blog of Roelof Rietbroek (PhD in geodesy), covering posts on science, opinion pieces, (peer-reviewed) publications and scientific projects and software"
    image: "/images/avatar.jpg" #for frontpage profile card
    about: "Welcome to Wobbly Earth, the homepage of Roelof Rietbroek"
    logo: "/images/WBlogo_64x64.png"
    website: "https://www.apmg.uni-bonn.de/personal/mitarbeiter/roelof"
    email: "roelof@wobbly.earth"
    twitter: "https://twitter.com/r_rietje"
    github: "https://github.com/strawpants/"
    gscholar: "https://scholar.google.com/citations?user=PojYuOAAAAAJ&hl=en"
#    linkedin: "https://linkedin.com/in/firstname_lastname/"
    facebook: "https://facebook.com/rrietbroek/"
    copyrightyear: "2018"
    frontpageposts: 3 #number of post cards to display on frontpage
    
